name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    # Stop actions on draft PRs
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  build-and-test:
    if: github.event.pull_request.draft == false
    name: ${{ matrix.platform.name }}-${{ matrix.build_type }}-SharedLibs${{ matrix.build_shared_libs }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [ "Debug" ]
        build_shared_libs: [ "OFF", "ON" ]
        platform: 
        - {
            name: "Ubuntu_GCC",
            os: ubuntu-24.04,
            targetFolder: "",
            exeExtension: "",
            cc: "gcc-14",
            cxx: "g++-14"
          }
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            targetFolder: "Debug/", # Must match build_type.
            exeExtension: ".exe",
            cc: "cl",
            cxx: "cl",
            generators: "Visual Studio 16 2019"
          }
        - {
            name: "macOS Latest Clang",
            os: macos-latest,
            targetFolder: "",
            exeExtension: "",
            cc: "clang",
            cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies on ubuntu
      if: startsWith(matrix.platform.name, 'Ubuntu_GCC')
      run: |
        sudo apt-get update
        sudo apt-get install cmake ${{ matrix.platform.cc }} ${{ matrix.platform.cxx }} qt6-base-dev libasound2-dev
        cmake --version
        gcc --version
        g++ --version

    - name: Install dependencies on macOS
      if: startsWith(matrix.platform.os, 'macos')
      run: |
        brew install cmake qt6
        cmake --version
        clang --version

    - name: Install Qt on Windows
      if: startsWith(matrix.platform.os, 'windows')
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        host: 'windows'

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_SHARED_LIBS=${{ matrix.build_shared_libs }}
      env:
        CC:   ${{ matrix.platform.cc }}
        CXX:  ${{ matrix.platform.cxx }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: BaseLibTest
      working-directory: build
      shell: bash
      run: Tests/BaseLib/${{ matrix.platform.targetFolder }}baseLibTests${{ matrix.platform.exeExtension }}

    - name: BabelWiresTest
      working-directory: build/Tests/BabelWiresLib
      shell: bash
      run: ./${{ matrix.platform.targetFolder }}babelWiresTests${{ matrix.platform.exeExtension }}

    - name: MusicLibTests
      working-directory: build
      shell: bash
      run: Domains/Music/Tests/MusicLib/${{ matrix.platform.targetFolder }}musicLibTests${{ matrix.platform.exeExtension }}

    - name: Seq2tapeLibTests
      working-directory: build
      shell: bash
      run: Domains/Music/Tests/Seq2tapeLib/${{ matrix.platform.targetFolder }}seq2tapeLibTests${{ matrix.platform.exeExtension }}

    - name: SmfTests
      working-directory: build/Domains/Music/Plugins/Smf/Tests
      shell: bash
      run: ./${{ matrix.platform.targetFolder }}SmfTests${{ matrix.platform.exeExtension }}
