name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    # Stop actions on draft PRs
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  build-and-test:
    if: github.event.pull_request.draft == false
    name: ${{ matrix.platform.name }}-${{ matrix.preset.name }}
    runs-on: ${{ matrix.platform.os }}
    env:
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
    strategy:
      fail-fast: false
      matrix:
        preset:
        - {
            name: "static-debug",
            preset: "static-debug"
          }
        - {
            name: "shared-debug",
            preset: "shared-debug"
          }
        platform: 
        - {
            name: "Ubuntu_GCC",
            os: ubuntu-24.04,
            cc: "gcc-14",
            cxx: "g++-14"
          }
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            cc: "cl",
            cxx: "cl"
          }
        - {
            name: "macOS Latest Clang",
            os: macos-latest,
            cc: "clang",
            cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Install dependencies on ubuntu
      if: startsWith(matrix.platform.name, 'Ubuntu_GCC')
      run: |
        sudo apt-get update
        sudo apt-get install cmake ${{ matrix.platform.cc }} ${{ matrix.platform.cxx }} qt6-base-dev libasound2-dev
        cmake --version
        ninja --version
        $CC --version
        $CXX --version

    - name: Install dependencies on macOS
      if: startsWith(matrix.platform.os, 'macos')
      run: |
        brew install cmake qt6
        cmake --version
        ninja --version
        clang --version

    - name: Install Qt on Windows
      if: startsWith(matrix.platform.os, 'windows')
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        host: 'windows'

    - name: Configure MSVC environment on Windows
      if: startsWith(matrix.platform.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset.preset }}

    - name: Run Tests
      run: ctest --preset ${{ matrix.preset.preset }}
